# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import examcentralapp.models
import examcentralapp.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.TextField(unique=True)),
                ('total_questions', models.IntegerField()),
                ('attempts_allowed', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('mark_per_qtn', models.IntegerField()),
                ('negative_per_qtn', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('question', models.TextField()),
                ('qtype', models.IntegerField(choices=[(1, b'Either Or Choice'), (2, b'True or False'), (3, b'More than one selection'), (4, b'Desciptive')], default=1)),
                ('qcategory', models.IntegerField(choices=[(1, b'General'), (2, b'Data Analysis'), (3, b'Language'), (4, b'Logical Reasoning')], default=1)),
                ('qpic', models.FileField(blank=True, null=True, upload_to=examcentralapp.models.qtn_directory_path)),
                ('answer', models.TextField(max_length=5000)),
                ('examname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examcentralapp.ExamName')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('correct_options', models.TextField(max_length=5000)),
                ('explanation', models.TextField(max_length=5000)),
                ('examname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examcentralapp.ExamName')),
            ],
        ),
        migrations.CreateModel(
            name='OptionA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('option', models.TextField(max_length=5000)),
                ('isright', models.BooleanField(default=False)),
                ('examname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examcentralapp.ExamName')),
            ],
        ),
        migrations.CreateModel(
            name='OptionB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('option', models.TextField(max_length=5000)),
                ('isright', models.BooleanField(default=False)),
                ('examname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examcentralapp.ExamName')),
            ],
        ),
        migrations.CreateModel(
            name='OptionC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('option', models.TextField(max_length=5000)),
                ('isright', models.BooleanField(default=False)),
                ('examname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examcentralapp.ExamName')),
            ],
        ),
        migrations.CreateModel(
            name='OptionD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('option', models.TextField(max_length=5000)),
                ('isright', models.BooleanField(default=False)),
                ('examname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examcentralapp.ExamName')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('examnames', models.ManyToManyField(to='examcentralapp.ExamName')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attemptid', models.IntegerField()),
                ('qid', models.IntegerField()),
                ('user_choices', models.TextField(max_length=5000)),
                ('user_explanation', models.TextField(max_length=5000)),
                ('isright', models.BooleanField(default=False)),
                ('examname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examcentralapp.ExamName')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=5000, null=True)),
                ('city', models.TextField(blank=True, max_length=500, null=True)),
                ('country', models.TextField(blank=True, max_length=500, null=True)),
                ('pincode', models.BigIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('aboutme', models.TextField(blank=True, max_length=5000, null=True)),
                ('profilepic', models.FileField(blank=True, null=True, storage=examcentralapp.storage.OverwriteStorage(), upload_to=examcentralapp.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examcentralapp.ExamName')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserScoreSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attemptid', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('total_questions', models.IntegerField()),
                ('answered_questions', models.IntegerField()),
                ('correctly_answered', models.IntegerField()),
                ('issubmitted', models.BooleanField(default=False)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('mark', models.DecimalField(decimal_places=2, max_digits=6)),
                ('examname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examcentralapp.ExamName')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
